# Generated by Django 3.2 on 2021-05-02 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matjip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='place',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 15, 14, 35, 813528)),
        ),
        migrations.AddField(
            model_name='place',
            name='num_visit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 15, 14, 35, 813545)),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
