# Generated by Django 3.2 on 2021-05-02 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matjip', '0002_auto_20210502_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 23, 18, 20, 763839)),
        ),
        migrations.AlterField(
            model_name='place',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 23, 18, 20, 763856)),
        ),
    ]
